version: '3.7'

x-mongo-model: &mongo-model
  image: mongo:4.4
  restart: unless-stopped

services:
  # mongo:
  #   <<: *mongo-model
  #   ports:
  #     - 27017:27017
  app:
    ports:
      - 10001:10001
    build:
      context: .
    command: python Puzzle_12/main.py
    volumes:
      - ./:/app



